--- @meta
---
---@class TodioConfig
---@field position?  "bottom" | "top" | "left" | "right" position of the loclist can be "bottom" | "top" | "left" | "right"
--
---@class TodioParsedTodo
---@field bufnr integer
---@field text string
---@field lnum integer
---@field col integer
---@field type "T" | "F" | "E" | "W" | "R"
--
---@class TodioTodo
---@field bufnr integer
---@field text string
---@field lnum integer
---@field col integer
---@field type "T" | "F" | "E" | "W" | "R"
--
---@class TodioQfList
---@field bufnr integer
---@field text string
---@field lnum integer
---@field col integer
---@field type "T" | "F" | "E" | "W" | "R"
--
---@class TodioLocList
---@field bufnr integer
---@field text string
---@field lnum integer
---@field col integer
---@field type "T" | "F" | "E" | "W" | "R"
